// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Shifty",
    defaultLocalization: "en",
    platforms: [
        .iOS("18.2")
    ],
    products: [
        .iOSApplication(
            name: "Shifty",
            targets: ["AppModule"],
            bundleIdentifier: "Nex-Dev.Shift",
            teamIdentifier: "ZM7H4XV93K",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .flower),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Sources")
            ]
        )
    ]
)